export type Language = 'fa' | 'en'
export const text = {
  fa: {
    allItems: 'همه موارد', scheduledCollection: 'وصول برنامه‌ریزی‌شده', thisMonth: 'این ماه', irr: 'ریال', kg: 'کیلوگرم', checkItems: 'فقره', usd: 'دلار', dueToday: '۳ سررسید امروز', twoWarehouses: '۲ انبار', updated: 'به‌روز',
    title: 'بازرگانی نخ امانی', dashboard: 'داشبورد', persons: 'تعریف اشخاص', yarns: 'تعریف نخ', purchaseOrders: 'سفارش خرید نخ', commerce: 'خرید نخ', purchases: 'خرید و واردات', inventory: 'موجودی انبار', sales: 'فروش', finance: 'دریافت و پرداخت', checks: 'مدیریت چک', partners: 'حساب شرکا', reports: 'گزارش‌ها', users: 'تعریف کاربران', dataBackup: 'تهیه و بازخوانی اطلاعات', settings: 'تنظیمات کاربر',
    openReceivables: 'مطالبات باز', inventoryValue: 'موجودی قابل فروش', checksDue: 'چک‌های نزدیک سررسید', partnerBalance: 'مانده شریک چینی', recentPurchases: 'آخرین فاکتورهای خرید', quickActions: 'عملیات سریع', newPurchase: 'فاکتور خرید جدید', newSale: 'فاکتور فروش جدید', receipt: 'دریافت وجه', payment: 'پرداخت وجه', search: 'جستجو در اسناد، اشخاص و نخ‌ها…', internalNo: 'شماره داخلی', invoiceNo: 'شماره فاکتور', date: 'تاریخ', supplier: 'تأمین‌کننده', netWeight: 'وزن خالص', total: 'جمع', status: 'وضعیت', draft: 'پیش‌نویس', posted: 'ثبت‌شده', login: 'ورود', email: 'ایمیل', password: 'رمز عبور', loginHint: 'کاربر نمونه: admin@yarntrade.local', loading: 'در حال دریافت…', noData: 'داده‌ای وجود ندارد', systemStatus: 'وضعیت سامانه', healthy: 'آماده'
  },
  en: {
    allItems: 'All items', scheduledCollection: 'Scheduled collection', thisMonth: 'This month', irr: 'IRR', kg: 'kg', checkItems: 'checks', usd: 'USD', dueToday: '3 due today', twoWarehouses: '2 warehouses', updated: 'Updated',
    title: 'Consignment Yarn Trade', dashboard: 'Dashboard', persons: 'People', yarns: 'Yarns', purchaseOrders: 'Yarn Purchase Orders', commerce: 'Yarn Purchase', purchases: 'Purchasing & Import', inventory: 'Inventory', sales: 'Sales', finance: 'Receipts & Payments', checks: 'Checks', partners: 'Partner Ledgers', reports: 'Reports', users: 'Users & Access', dataBackup: 'Backup & Restore', settings: 'User Settings',
    openReceivables: 'Open receivables', inventoryValue: 'Available stock', checksDue: 'Checks due soon', partnerBalance: 'Chinese partner balance', recentPurchases: 'Recent purchase invoices', quickActions: 'Quick actions', newPurchase: 'New purchase invoice', newSale: 'New sales invoice', receipt: 'Receive money', payment: 'Pay money', search: 'Search documents, persons and yarn…', internalNo: 'Internal no.', invoiceNo: 'Invoice no.', date: 'Date', supplier: 'Supplier', netWeight: 'Net weight', total: 'Total', status: 'Status', draft: 'Draft', posted: 'Posted', login: 'Sign in', email: 'Email', password: 'Password', loginHint: 'Demo user: admin@yarntrade.local', loading: 'Loading…', noData: 'No data', systemStatus: 'System status', healthy: 'Ready'
  }
} as const
